apiVersion: v2
name: openlore
description: Enterprise Helm Chart for OpenLore - Git for 3D worlds, game lore, and Hollywood pipelines.
type: application
version: 1.0.1
appVersion: "1.0.1"
maintainers:
  - name: OpenLore Engineering
    email: engineering@openlore.io
